GRANT USAGE ON SCHEMA rbs TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA rbs TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA rbs TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA rbs TO "apps";